// AUTOGENERATED FILE

struct call_attrs_t { 
	uint64_t disabled;
	uint64_t timeout;
	uint64_t prog_timeout;
	uint64_t ignore_return;
	uint64_t breaks_returns;
};

struct call_props_t { 
	int fail_nth;
	bool async;
	int rerun;
};

#define read_call_props_t(var, reader) { \
	(var).fail_nth = (int)(reader); \
	(var).async = (bool)(reader); \
	(var).rerun = (int)(reader); \
}


#if GOOS_akaros
#define GOOS "akaros"

#if GOARCH_amd64
#define GOARCH "amd64"
#define SYZ_REVISION "1afc408b879b315ebcb86954b10af7de4f68a0dd"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 0
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#endif

#endif

#if GOOS_darwin
#define GOOS "darwin"

#if GOARCH_amd64
#define GOARCH "amd64"
#define SYZ_REVISION "c7b59d01274d649acd2c7abcc0fd0bd2a35700f9"
#define SYZ_EXECUTOR_USES_FORK_SERVER 0
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 8589934592
#endif

#endif

#if GOOS_freebsd
#define GOOS "freebsd"

#if GOARCH_386
#define GOARCH "386"
#define SYZ_REVISION "abe4a7da3f5eb8f2e8a23e7da96a5a2017e65615"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 268435456
#ifndef SYS___realpathat
#define SYS___realpathat 574
#endif
#ifndef SYS___specialfd
#define SYS___specialfd 577
#endif
#ifndef SYS_aio_readv
#define SYS_aio_readv 579
#endif
#ifndef SYS_aio_writev
#define SYS_aio_writev 578
#endif
#ifndef SYS_copy_file_range
#define SYS_copy_file_range 569
#endif
#ifndef SYS_freebsd12_shm_open
#define SYS_freebsd12_shm_open 482
#endif
#ifndef SYS_fspacectl
#define SYS_fspacectl 580
#endif
#ifndef SYS_shm_open2
#define SYS_shm_open2 571
#endif
#ifndef SYS_shm_rename
#define SYS_shm_rename 572
#endif
#endif

#if GOARCH_amd64
#define GOARCH "amd64"
#define SYZ_REVISION "78456ecbe16c01afb1c73ccd379dc26637f37631"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef SYS___realpathat
#define SYS___realpathat 574
#endif
#ifndef SYS___specialfd
#define SYS___specialfd 577
#endif
#ifndef SYS_aio_readv
#define SYS_aio_readv 579
#endif
#ifndef SYS_aio_writev
#define SYS_aio_writev 578
#endif
#ifndef SYS_copy_file_range
#define SYS_copy_file_range 569
#endif
#ifndef SYS_freebsd12_shm_open
#define SYS_freebsd12_shm_open 482
#endif
#ifndef SYS_fspacectl
#define SYS_fspacectl 580
#endif
#ifndef SYS_shm_open2
#define SYS_shm_open2 571
#endif
#ifndef SYS_shm_rename
#define SYS_shm_rename 572
#endif
#endif

#endif

#if GOOS_fuchsia
#define GOOS "fuchsia"

#if GOARCH_amd64
#define GOARCH "amd64"
#define SYZ_REVISION "1870a8e8b3f060b3d229b01d955a21de3fd7c937"
#define SYZ_EXECUTOR_USES_FORK_SERVER 0
#define SYZ_EXECUTOR_USES_SHMEM 0
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#endif

#if GOARCH_arm64
#define GOARCH "arm64"
#define SYZ_REVISION "d5f287b7875d5b4a64836a0bcbb99f3fa4ee61d7"
#define SYZ_EXECUTOR_USES_FORK_SERVER 0
#define SYZ_EXECUTOR_USES_SHMEM 0
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#endif

#endif

#if GOOS_linux
#define GOOS "linux"

#if GOARCH_386
#define GOARCH "386"
#define SYZ_REVISION "3a6ce38e0fe090fafda8d6216ca1f3ba53be2d99"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef __NR_accept4
#define __NR_accept4 364
#endif
#ifndef __NR_add_key
#define __NR_add_key 286
#endif
#ifndef __NR_arch_prctl
#define __NR_arch_prctl 384
#endif
#ifndef __NR_bind
#define __NR_bind 361
#endif
#ifndef __NR_bpf
#define __NR_bpf 357
#endif
#ifndef __NR_close
#define __NR_close 6
#endif
#ifndef __NR_connect
#define __NR_connect 362
#endif
#ifndef __NR_execve
#define __NR_execve 11
#endif
#ifndef __NR_execveat
#define __NR_execveat 358
#endif
#ifndef __NR_fanotify_init
#define __NR_fanotify_init 338
#endif
#ifndef __NR_fanotify_mark
#define __NR_fanotify_mark 339
#endif
#ifndef __NR_fgetxattr
#define __NR_fgetxattr 231
#endif
#ifndef __NR_flistxattr
#define __NR_flistxattr 234
#endif
#ifndef __NR_fremovexattr
#define __NR_fremovexattr 237
#endif
#ifndef __NR_fsetxattr
#define __NR_fsetxattr 228
#endif
#ifndef __NR_futex
#define __NR_futex 240
#endif
#ifndef __NR_futex_waitv
#define __NR_futex_waitv 449
#endif
#ifndef __NR_get_robust_list
#define __NR_get_robust_list 312
#endif
#ifndef __NR_getpeername
#define __NR_getpeername 368
#endif
#ifndef __NR_getsockname
#define __NR_getsockname 367
#endif
#ifndef __NR_getsockopt
#define __NR_getsockopt 365
#endif
#ifndef __NR_getxattr
#define __NR_getxattr 229
#endif
#ifndef __NR_inotify_add_watch
#define __NR_inotify_add_watch 292
#endif
#ifndef __NR_inotify_init
#define __NR_inotify_init 291
#endif
#ifndef __NR_inotify_init1
#define __NR_inotify_init1 332
#endif
#ifndef __NR_inotify_rm_watch
#define __NR_inotify_rm_watch 293
#endif
#ifndef __NR_io_cancel
#define __NR_io_cancel 249
#endif
#ifndef __NR_io_destroy
#define __NR_io_destroy 246
#endif
#ifndef __NR_io_getevents
#define __NR_io_getevents 247
#endif
#ifndef __NR_io_pgetevents
#define __NR_io_pgetevents 385
#endif
#ifndef __NR_io_setup
#define __NR_io_setup 245
#endif
#ifndef __NR_io_submit
#define __NR_io_submit 248
#endif
#ifndef __NR_io_uring_enter
#define __NR_io_uring_enter 426
#endif
#ifndef __NR_io_uring_register
#define __NR_io_uring_register 427
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif
#ifndef __NR_ioctl
#define __NR_ioctl 54
#endif
#ifndef __NR_keyctl
#define __NR_keyctl 288
#endif
#ifndef __NR_landlock_add_rule
#define __NR_landlock_add_rule 445
#endif
#ifndef __NR_landlock_create_ruleset
#define __NR_landlock_create_ruleset 444
#endif
#ifndef __NR_landlock_restrict_self
#define __NR_landlock_restrict_self 446
#endif
#ifndef __NR_lgetxattr
#define __NR_lgetxattr 230
#endif
#ifndef __NR_listen
#define __NR_listen 363
#endif
#ifndef __NR_listxattr
#define __NR_listxattr 232
#endif
#ifndef __NR_llistxattr
#define __NR_llistxattr 233
#endif
#ifndef __NR_lremovexattr
#define __NR_lremovexattr 236
#endif
#ifndef __NR_lsetxattr
#define __NR_lsetxattr 227
#endif
#ifndef __NR_mkdirat
#define __NR_mkdirat 296
#endif
#ifndef __NR_mmap
#define __NR_mmap 192
#endif
#ifndef __NR_mount
#define __NR_mount 21
#endif
#ifndef __NR_msgctl
#define __NR_msgctl 402
#endif
#ifndef __NR_msgget
#define __NR_msgget 399
#endif
#ifndef __NR_msgrcv
#define __NR_msgrcv 401
#endif
#ifndef __NR_msgsnd
#define __NR_msgsnd 400
#endif
#ifndef __NR_openat
#define __NR_openat 295
#endif
#ifndef __NR_perf_event_open
#define __NR_perf_event_open 336
#endif
#ifndef __NR_pipe2
#define __NR_pipe2 331
#endif
#ifndef __NR_prctl
#define __NR_prctl 172
#endif
#ifndef __NR_read
#define __NR_read 3
#endif
#ifndef __NR_recvfrom
#define __NR_recvfrom 371
#endif
#ifndef __NR_recvmmsg
#define __NR_recvmmsg 337
#endif
#ifndef __NR_recvmsg
#define __NR_recvmsg 372
#endif
#ifndef __NR_removexattr
#define __NR_removexattr 235
#endif
#ifndef __NR_request_key
#define __NR_request_key 287
#endif
#ifndef __NR_seccomp
#define __NR_seccomp 354
#endif
#ifndef __NR_semctl
#define __NR_semctl 394
#endif
#ifndef __NR_semget
#define __NR_semget 393
#endif
#ifndef __NR_sendmmsg
#define __NR_sendmmsg 345
#endif
#ifndef __NR_sendmsg
#define __NR_sendmsg 370
#endif
#ifndef __NR_sendto
#define __NR_sendto 369
#endif
#ifndef __NR_set_robust_list
#define __NR_set_robust_list 311
#endif
#ifndef __NR_setns
#define __NR_setns 346
#endif
#ifndef __NR_setsockopt
#define __NR_setsockopt 366
#endif
#ifndef __NR_setxattr
#define __NR_setxattr 226
#endif
#ifndef __NR_shmat
#define __NR_shmat 397
#endif
#ifndef __NR_shmctl
#define __NR_shmctl 396
#endif
#ifndef __NR_shmdt
#define __NR_shmdt 398
#endif
#ifndef __NR_shmget
#define __NR_shmget 395
#endif
#ifndef __NR_shutdown
#define __NR_shutdown 373
#endif
#ifndef __NR_socket
#define __NR_socket 359
#endif
#ifndef __NR_socketpair
#define __NR_socketpair 360
#endif
#ifndef __NR_unlinkat
#define __NR_unlinkat 301
#endif
#ifndef __NR_unshare
#define __NR_unshare 310
#endif
#ifndef __NR_userfaultfd
#define __NR_userfaultfd 374
#endif
#ifndef __NR_write
#define __NR_write 4
#endif
#endif

#if GOARCH_amd64
#define GOARCH "amd64"
#define SYZ_REVISION "fdba5d0e10281d2d9df000039d3a7fb78a8328d4"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef __NR_bpf
#define __NR_bpf 321
#endif
#ifndef __NR_clone3
#define __NR_clone3 435
#endif
#ifndef __NR_close_range
#define __NR_close_range 436
#endif
#ifndef __NR_copy_file_range
#define __NR_copy_file_range 326
#endif
#ifndef __NR_epoll_pwait2
#define __NR_epoll_pwait2 441
#endif
#ifndef __NR_execveat
#define __NR_execveat 322
#endif
#ifndef __NR_faccessat2
#define __NR_faccessat2 439
#endif
#ifndef __NR_finit_module
#define __NR_finit_module 313
#endif
#ifndef __NR_fsconfig
#define __NR_fsconfig 431
#endif
#ifndef __NR_fsmount
#define __NR_fsmount 432
#endif
#ifndef __NR_fsopen
#define __NR_fsopen 430
#endif
#ifndef __NR_fspick
#define __NR_fspick 433
#endif
#ifndef __NR_futex_waitv
#define __NR_futex_waitv 449
#endif
#ifndef __NR_getrandom
#define __NR_getrandom 318
#endif
#ifndef __NR_io_pgetevents
#define __NR_io_pgetevents 333
#endif
#ifndef __NR_io_uring_enter
#define __NR_io_uring_enter 426
#endif
#ifndef __NR_io_uring_register
#define __NR_io_uring_register 427
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif
#ifndef __NR_landlock_add_rule
#define __NR_landlock_add_rule 445
#endif
#ifndef __NR_landlock_create_ruleset
#define __NR_landlock_create_ruleset 444
#endif
#ifndef __NR_landlock_restrict_self
#define __NR_landlock_restrict_self 446
#endif
#ifndef __NR_membarrier
#define __NR_membarrier 324
#endif
#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif
#ifndef __NR_memfd_secret
#define __NR_memfd_secret 447
#endif
#ifndef __NR_mlock2
#define __NR_mlock2 325
#endif
#ifndef __NR_mount_setattr
#define __NR_mount_setattr 442
#endif
#ifndef __NR_move_mount
#define __NR_move_mount 429
#endif
#ifndef __NR_open_tree
#define __NR_open_tree 428
#endif
#ifndef __NR_openat2
#define __NR_openat2 437
#endif
#ifndef __NR_pidfd_getfd
#define __NR_pidfd_getfd 438
#endif
#ifndef __NR_pidfd_open
#define __NR_pidfd_open 434
#endif
#ifndef __NR_pidfd_send_signal
#define __NR_pidfd_send_signal 424
#endif
#ifndef __NR_pkey_alloc
#define __NR_pkey_alloc 330
#endif
#ifndef __NR_pkey_free
#define __NR_pkey_free 331
#endif
#ifndef __NR_pkey_mprotect
#define __NR_pkey_mprotect 329
#endif
#ifndef __NR_preadv2
#define __NR_preadv2 327
#endif
#ifndef __NR_process_madvise
#define __NR_process_madvise 440
#endif
#ifndef __NR_process_mrelease
#define __NR_process_mrelease 448
#endif
#ifndef __NR_pwritev2
#define __NR_pwritev2 328
#endif
#ifndef __NR_renameat2
#define __NR_renameat2 316
#endif
#ifndef __NR_rseq
#define __NR_rseq 334
#endif
#ifndef __NR_sched_getattr
#define __NR_sched_getattr 315
#endif
#ifndef __NR_sched_setattr
#define __NR_sched_setattr 314
#endif
#ifndef __NR_seccomp
#define __NR_seccomp 317
#endif
#ifndef __NR_statx
#define __NR_statx 332
#endif
#ifndef __NR_userfaultfd
#define __NR_userfaultfd 323
#endif
#endif

#if GOARCH_arm
#define GOARCH "arm"
#define SYZ_REVISION "20a0890f56dffc59e109716b4c7219a17b65702f"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef __NR_accept
#define __NR_accept 285
#endif
#ifndef __NR_accept4
#define __NR_accept4 366
#endif
#ifndef __NR_add_key
#define __NR_add_key 309
#endif
#ifndef __NR_bind
#define __NR_bind 282
#endif
#ifndef __NR_bpf
#define __NR_bpf 386
#endif
#ifndef __NR_close
#define __NR_close 6
#endif
#ifndef __NR_connect
#define __NR_connect 283
#endif
#ifndef __NR_execve
#define __NR_execve 11
#endif
#ifndef __NR_execveat
#define __NR_execveat 387
#endif
#ifndef __NR_fanotify_init
#define __NR_fanotify_init 367
#endif
#ifndef __NR_fanotify_mark
#define __NR_fanotify_mark 368
#endif
#ifndef __NR_fgetxattr
#define __NR_fgetxattr 231
#endif
#ifndef __NR_flistxattr
#define __NR_flistxattr 234
#endif
#ifndef __NR_fremovexattr
#define __NR_fremovexattr 237
#endif
#ifndef __NR_fsetxattr
#define __NR_fsetxattr 228
#endif
#ifndef __NR_futex
#define __NR_futex 240
#endif
#ifndef __NR_futex_waitv
#define __NR_futex_waitv 449
#endif
#ifndef __NR_get_robust_list
#define __NR_get_robust_list 339
#endif
#ifndef __NR_getpeername
#define __NR_getpeername 287
#endif
#ifndef __NR_getsockname
#define __NR_getsockname 286
#endif
#ifndef __NR_getsockopt
#define __NR_getsockopt 295
#endif
#ifndef __NR_getxattr
#define __NR_getxattr 229
#endif
#ifndef __NR_inotify_add_watch
#define __NR_inotify_add_watch 317
#endif
#ifndef __NR_inotify_init
#define __NR_inotify_init 316
#endif
#ifndef __NR_inotify_init1
#define __NR_inotify_init1 360
#endif
#ifndef __NR_inotify_rm_watch
#define __NR_inotify_rm_watch 318
#endif
#ifndef __NR_io_cancel
#define __NR_io_cancel 247
#endif
#ifndef __NR_io_destroy
#define __NR_io_destroy 244
#endif
#ifndef __NR_io_getevents
#define __NR_io_getevents 245
#endif
#ifndef __NR_io_pgetevents
#define __NR_io_pgetevents 399
#endif
#ifndef __NR_io_setup
#define __NR_io_setup 243
#endif
#ifndef __NR_io_submit
#define __NR_io_submit 246
#endif
#ifndef __NR_io_uring_enter
#define __NR_io_uring_enter 426
#endif
#ifndef __NR_io_uring_register
#define __NR_io_uring_register 427
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif
#ifndef __NR_ioctl
#define __NR_ioctl 54
#endif
#ifndef __NR_keyctl
#define __NR_keyctl 311
#endif
#ifndef __NR_landlock_add_rule
#define __NR_landlock_add_rule 445
#endif
#ifndef __NR_landlock_create_ruleset
#define __NR_landlock_create_ruleset 444
#endif
#ifndef __NR_landlock_restrict_self
#define __NR_landlock_restrict_self 446
#endif
#ifndef __NR_lgetxattr
#define __NR_lgetxattr 230
#endif
#ifndef __NR_listen
#define __NR_listen 284
#endif
#ifndef __NR_listxattr
#define __NR_listxattr 232
#endif
#ifndef __NR_llistxattr
#define __NR_llistxattr 233
#endif
#ifndef __NR_lremovexattr
#define __NR_lremovexattr 236
#endif
#ifndef __NR_lsetxattr
#define __NR_lsetxattr 227
#endif
#ifndef __NR_mkdirat
#define __NR_mkdirat 323
#endif
#ifndef __NR_mmap
#define __NR_mmap 192
#endif
#ifndef __NR_mount
#define __NR_mount 21
#endif
#ifndef __NR_msgctl
#define __NR_msgctl 304
#endif
#ifndef __NR_msgget
#define __NR_msgget 303
#endif
#ifndef __NR_msgrcv
#define __NR_msgrcv 302
#endif
#ifndef __NR_msgsnd
#define __NR_msgsnd 301
#endif
#ifndef __NR_openat
#define __NR_openat 322
#endif
#ifndef __NR_perf_event_open
#define __NR_perf_event_open 364
#endif
#ifndef __NR_pipe2
#define __NR_pipe2 359
#endif
#ifndef __NR_prctl
#define __NR_prctl 172
#endif
#ifndef __NR_read
#define __NR_read 3
#endif
#ifndef __NR_recvfrom
#define __NR_recvfrom 292
#endif
#ifndef __NR_recvmmsg
#define __NR_recvmmsg 365
#endif
#ifndef __NR_recvmsg
#define __NR_recvmsg 297
#endif
#ifndef __NR_removexattr
#define __NR_removexattr 235
#endif
#ifndef __NR_request_key
#define __NR_request_key 310
#endif
#ifndef __NR_seccomp
#define __NR_seccomp 383
#endif
#ifndef __NR_semctl
#define __NR_semctl 300
#endif
#ifndef __NR_semget
#define __NR_semget 299
#endif
#ifndef __NR_semop
#define __NR_semop 298
#endif
#ifndef __NR_semtimedop
#define __NR_semtimedop 312
#endif
#ifndef __NR_sendmmsg
#define __NR_sendmmsg 374
#endif
#ifndef __NR_sendmsg
#define __NR_sendmsg 296
#endif
#ifndef __NR_sendto
#define __NR_sendto 290
#endif
#ifndef __NR_set_robust_list
#define __NR_set_robust_list 338
#endif
#ifndef __NR_setns
#define __NR_setns 375
#endif
#ifndef __NR_setsockopt
#define __NR_setsockopt 294
#endif
#ifndef __NR_setxattr
#define __NR_setxattr 226
#endif
#ifndef __NR_shmat
#define __NR_shmat 305
#endif
#ifndef __NR_shmctl
#define __NR_shmctl 308
#endif
#ifndef __NR_shmdt
#define __NR_shmdt 306
#endif
#ifndef __NR_shmget
#define __NR_shmget 307
#endif
#ifndef __NR_shutdown
#define __NR_shutdown 293
#endif
#ifndef __NR_socket
#define __NR_socket 281
#endif
#ifndef __NR_socketpair
#define __NR_socketpair 288
#endif
#ifndef __NR_unlinkat
#define __NR_unlinkat 328
#endif
#ifndef __NR_unshare
#define __NR_unshare 337
#endif
#ifndef __NR_userfaultfd
#define __NR_userfaultfd 388
#endif
#ifndef __NR_write
#define __NR_write 4
#endif
#endif

#if GOARCH_arm64
#define GOARCH "arm64"
#define SYZ_REVISION "70bf79abc3188a595264439aec80cb4884637f0c"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef __NR_accept
#define __NR_accept 202
#endif
#ifndef __NR_accept4
#define __NR_accept4 242
#endif
#ifndef __NR_add_key
#define __NR_add_key 217
#endif
#ifndef __NR_bind
#define __NR_bind 200
#endif
#ifndef __NR_bpf
#define __NR_bpf 280
#endif
#ifndef __NR_close
#define __NR_close 57
#endif
#ifndef __NR_connect
#define __NR_connect 203
#endif
#ifndef __NR_execve
#define __NR_execve 221
#endif
#ifndef __NR_execveat
#define __NR_execveat 281
#endif
#ifndef __NR_fanotify_init
#define __NR_fanotify_init 262
#endif
#ifndef __NR_fanotify_mark
#define __NR_fanotify_mark 263
#endif
#ifndef __NR_fgetxattr
#define __NR_fgetxattr 10
#endif
#ifndef __NR_flistxattr
#define __NR_flistxattr 13
#endif
#ifndef __NR_fremovexattr
#define __NR_fremovexattr 16
#endif
#ifndef __NR_fsetxattr
#define __NR_fsetxattr 7
#endif
#ifndef __NR_futex
#define __NR_futex 98
#endif
#ifndef __NR_futex_waitv
#define __NR_futex_waitv 449
#endif
#ifndef __NR_get_robust_list
#define __NR_get_robust_list 100
#endif
#ifndef __NR_getpeername
#define __NR_getpeername 205
#endif
#ifndef __NR_getsockname
#define __NR_getsockname 204
#endif
#ifndef __NR_getsockopt
#define __NR_getsockopt 209
#endif
#ifndef __NR_getxattr
#define __NR_getxattr 8
#endif
#ifndef __NR_inotify_add_watch
#define __NR_inotify_add_watch 27
#endif
#ifndef __NR_inotify_init1
#define __NR_inotify_init1 26
#endif
#ifndef __NR_inotify_rm_watch
#define __NR_inotify_rm_watch 28
#endif
#ifndef __NR_io_cancel
#define __NR_io_cancel 3
#endif
#ifndef __NR_io_destroy
#define __NR_io_destroy 1
#endif
#ifndef __NR_io_getevents
#define __NR_io_getevents 4
#endif
#ifndef __NR_io_pgetevents
#define __NR_io_pgetevents 292
#endif
#ifndef __NR_io_setup
#define __NR_io_setup 0
#endif
#ifndef __NR_io_submit
#define __NR_io_submit 2
#endif
#ifndef __NR_io_uring_enter
#define __NR_io_uring_enter 426
#endif
#ifndef __NR_io_uring_register
#define __NR_io_uring_register 427
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif
#ifndef __NR_ioctl
#define __NR_ioctl 29
#endif
#ifndef __NR_keyctl
#define __NR_keyctl 219
#endif
#ifndef __NR_landlock_add_rule
#define __NR_landlock_add_rule 445
#endif
#ifndef __NR_landlock_create_ruleset
#define __NR_landlock_create_ruleset 444
#endif
#ifndef __NR_landlock_restrict_self
#define __NR_landlock_restrict_self 446
#endif
#ifndef __NR_lgetxattr
#define __NR_lgetxattr 9
#endif
#ifndef __NR_listen
#define __NR_listen 201
#endif
#ifndef __NR_listxattr
#define __NR_listxattr 11
#endif
#ifndef __NR_llistxattr
#define __NR_llistxattr 12
#endif
#ifndef __NR_lremovexattr
#define __NR_lremovexattr 15
#endif
#ifndef __NR_lsetxattr
#define __NR_lsetxattr 6
#endif
#ifndef __NR_mkdirat
#define __NR_mkdirat 34
#endif
#ifndef __NR_mmap
#define __NR_mmap 222
#endif
#ifndef __NR_mount
#define __NR_mount 40
#endif
#ifndef __NR_msgctl
#define __NR_msgctl 187
#endif
#ifndef __NR_msgget
#define __NR_msgget 186
#endif
#ifndef __NR_msgrcv
#define __NR_msgrcv 188
#endif
#ifndef __NR_msgsnd
#define __NR_msgsnd 189
#endif
#ifndef __NR_openat
#define __NR_openat 56
#endif
#ifndef __NR_perf_event_open
#define __NR_perf_event_open 241
#endif
#ifndef __NR_pipe2
#define __NR_pipe2 59
#endif
#ifndef __NR_prctl
#define __NR_prctl 167
#endif
#ifndef __NR_read
#define __NR_read 63
#endif
#ifndef __NR_recvfrom
#define __NR_recvfrom 207
#endif
#ifndef __NR_recvmmsg
#define __NR_recvmmsg 243
#endif
#ifndef __NR_recvmsg
#define __NR_recvmsg 212
#endif
#ifndef __NR_removexattr
#define __NR_removexattr 14
#endif
#ifndef __NR_request_key
#define __NR_request_key 218
#endif
#ifndef __NR_seccomp
#define __NR_seccomp 277
#endif
#ifndef __NR_semctl
#define __NR_semctl 191
#endif
#ifndef __NR_semget
#define __NR_semget 190
#endif
#ifndef __NR_semop
#define __NR_semop 193
#endif
#ifndef __NR_semtimedop
#define __NR_semtimedop 192
#endif
#ifndef __NR_sendmmsg
#define __NR_sendmmsg 269
#endif
#ifndef __NR_sendmsg
#define __NR_sendmsg 211
#endif
#ifndef __NR_sendto
#define __NR_sendto 206
#endif
#ifndef __NR_set_robust_list
#define __NR_set_robust_list 99
#endif
#ifndef __NR_setns
#define __NR_setns 268
#endif
#ifndef __NR_setsockopt
#define __NR_setsockopt 208
#endif
#ifndef __NR_setxattr
#define __NR_setxattr 5
#endif
#ifndef __NR_shmat
#define __NR_shmat 196
#endif
#ifndef __NR_shmctl
#define __NR_shmctl 195
#endif
#ifndef __NR_shmdt
#define __NR_shmdt 197
#endif
#ifndef __NR_shmget
#define __NR_shmget 194
#endif
#ifndef __NR_shutdown
#define __NR_shutdown 210
#endif
#ifndef __NR_socket
#define __NR_socket 198
#endif
#ifndef __NR_socketpair
#define __NR_socketpair 199
#endif
#ifndef __NR_unlinkat
#define __NR_unlinkat 35
#endif
#ifndef __NR_unshare
#define __NR_unshare 97
#endif
#ifndef __NR_userfaultfd
#define __NR_userfaultfd 282
#endif
#ifndef __NR_write
#define __NR_write 64
#endif
#endif

#if GOARCH_mips64le
#define GOARCH "mips64le"
#define SYZ_REVISION "727dd98c5f3b70f6767fee3754e87172c804bc28"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef __NR_accept
#define __NR_accept 5042
#endif
#ifndef __NR_accept4
#define __NR_accept4 5293
#endif
#ifndef __NR_add_key
#define __NR_add_key 5239
#endif
#ifndef __NR_bind
#define __NR_bind 5048
#endif
#ifndef __NR_bpf
#define __NR_bpf 5315
#endif
#ifndef __NR_close
#define __NR_close 5003
#endif
#ifndef __NR_connect
#define __NR_connect 5041
#endif
#ifndef __NR_execve
#define __NR_execve 5057
#endif
#ifndef __NR_execveat
#define __NR_execveat 5316
#endif
#ifndef __NR_fanotify_init
#define __NR_fanotify_init 5295
#endif
#ifndef __NR_fanotify_mark
#define __NR_fanotify_mark 5296
#endif
#ifndef __NR_fgetxattr
#define __NR_fgetxattr 5185
#endif
#ifndef __NR_flistxattr
#define __NR_flistxattr 5188
#endif
#ifndef __NR_fremovexattr
#define __NR_fremovexattr 5191
#endif
#ifndef __NR_fsetxattr
#define __NR_fsetxattr 5182
#endif
#ifndef __NR_futex
#define __NR_futex 5194
#endif
#ifndef __NR_futex_waitv
#define __NR_futex_waitv 5449
#endif
#ifndef __NR_get_robust_list
#define __NR_get_robust_list 5269
#endif
#ifndef __NR_getpeername
#define __NR_getpeername 5051
#endif
#ifndef __NR_getsockname
#define __NR_getsockname 5050
#endif
#ifndef __NR_getsockopt
#define __NR_getsockopt 5054
#endif
#ifndef __NR_getxattr
#define __NR_getxattr 5183
#endif
#ifndef __NR_inotify_add_watch
#define __NR_inotify_add_watch 5244
#endif
#ifndef __NR_inotify_init
#define __NR_inotify_init 5243
#endif
#ifndef __NR_inotify_init1
#define __NR_inotify_init1 5288
#endif
#ifndef __NR_inotify_rm_watch
#define __NR_inotify_rm_watch 5245
#endif
#ifndef __NR_io_cancel
#define __NR_io_cancel 5204
#endif
#ifndef __NR_io_destroy
#define __NR_io_destroy 5201
#endif
#ifndef __NR_io_getevents
#define __NR_io_getevents 5202
#endif
#ifndef __NR_io_pgetevents
#define __NR_io_pgetevents 5328
#endif
#ifndef __NR_io_setup
#define __NR_io_setup 5200
#endif
#ifndef __NR_io_submit
#define __NR_io_submit 5203
#endif
#ifndef __NR_io_uring_enter
#define __NR_io_uring_enter 5426
#endif
#ifndef __NR_io_uring_register
#define __NR_io_uring_register 5427
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 5425
#endif
#ifndef __NR_ioctl
#define __NR_ioctl 5015
#endif
#ifndef __NR_keyctl
#define __NR_keyctl 5241
#endif
#ifndef __NR_landlock_add_rule
#define __NR_landlock_add_rule 5445
#endif
#ifndef __NR_landlock_create_ruleset
#define __NR_landlock_create_ruleset 5444
#endif
#ifndef __NR_landlock_restrict_self
#define __NR_landlock_restrict_self 5446
#endif
#ifndef __NR_lgetxattr
#define __NR_lgetxattr 5184
#endif
#ifndef __NR_listen
#define __NR_listen 5049
#endif
#ifndef __NR_listxattr
#define __NR_listxattr 5186
#endif
#ifndef __NR_llistxattr
#define __NR_llistxattr 5187
#endif
#ifndef __NR_lremovexattr
#define __NR_lremovexattr 5190
#endif
#ifndef __NR_lsetxattr
#define __NR_lsetxattr 5181
#endif
#ifndef __NR_mkdirat
#define __NR_mkdirat 5248
#endif
#ifndef __NR_mmap
#define __NR_mmap 5009
#endif
#ifndef __NR_mount
#define __NR_mount 5160
#endif
#ifndef __NR_msgctl
#define __NR_msgctl 5069
#endif
#ifndef __NR_msgget
#define __NR_msgget 5066
#endif
#ifndef __NR_msgrcv
#define __NR_msgrcv 5068
#endif
#ifndef __NR_msgsnd
#define __NR_msgsnd 5067
#endif
#ifndef __NR_openat
#define __NR_openat 5247
#endif
#ifndef __NR_perf_event_open
#define __NR_perf_event_open 5292
#endif
#ifndef __NR_pipe2
#define __NR_pipe2 5287
#endif
#ifndef __NR_prctl
#define __NR_prctl 5153
#endif
#ifndef __NR_read
#define __NR_read 5000
#endif
#ifndef __NR_recvfrom
#define __NR_recvfrom 5044
#endif
#ifndef __NR_recvmmsg
#define __NR_recvmmsg 5294
#endif
#ifndef __NR_recvmsg
#define __NR_recvmsg 5046
#endif
#ifndef __NR_removexattr
#define __NR_removexattr 5189
#endif
#ifndef __NR_request_key
#define __NR_request_key 5240
#endif
#ifndef __NR_seccomp
#define __NR_seccomp 5312
#endif
#ifndef __NR_semctl
#define __NR_semctl 5064
#endif
#ifndef __NR_semget
#define __NR_semget 5062
#endif
#ifndef __NR_semop
#define __NR_semop 5063
#endif
#ifndef __NR_semtimedop
#define __NR_semtimedop 5214
#endif
#ifndef __NR_sendmmsg
#define __NR_sendmmsg 5302
#endif
#ifndef __NR_sendmsg
#define __NR_sendmsg 5045
#endif
#ifndef __NR_sendto
#define __NR_sendto 5043
#endif
#ifndef __NR_set_robust_list
#define __NR_set_robust_list 5268
#endif
#ifndef __NR_setns
#define __NR_setns 5303
#endif
#ifndef __NR_setsockopt
#define __NR_setsockopt 5053
#endif
#ifndef __NR_setxattr
#define __NR_setxattr 5180
#endif
#ifndef __NR_shmat
#define __NR_shmat 5029
#endif
#ifndef __NR_shmctl
#define __NR_shmctl 5030
#endif
#ifndef __NR_shmdt
#define __NR_shmdt 5065
#endif
#ifndef __NR_shmget
#define __NR_shmget 5028
#endif
#ifndef __NR_shutdown
#define __NR_shutdown 5047
#endif
#ifndef __NR_socket
#define __NR_socket 5040
#endif
#ifndef __NR_socketpair
#define __NR_socketpair 5052
#endif
#ifndef __NR_unlinkat
#define __NR_unlinkat 5253
#endif
#ifndef __NR_unshare
#define __NR_unshare 5262
#endif
#ifndef __NR_userfaultfd
#define __NR_userfaultfd 5317
#endif
#ifndef __NR_write
#define __NR_write 5001
#endif
#endif

#if GOARCH_ppc64le
#define GOARCH "ppc64le"
#define SYZ_REVISION "7f88cf139171a0081bffa21877addff772f6bc97"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 65536
#define SYZ_NUM_PAGES 256
#define SYZ_DATA_OFFSET 536870912
#ifndef __NR_accept
#define __NR_accept 330
#endif
#ifndef __NR_accept4
#define __NR_accept4 344
#endif
#ifndef __NR_add_key
#define __NR_add_key 269
#endif
#ifndef __NR_bind
#define __NR_bind 327
#endif
#ifndef __NR_bpf
#define __NR_bpf 361
#endif
#ifndef __NR_close
#define __NR_close 6
#endif
#ifndef __NR_connect
#define __NR_connect 328
#endif
#ifndef __NR_execve
#define __NR_execve 11
#endif
#ifndef __NR_execveat
#define __NR_execveat 362
#endif
#ifndef __NR_fanotify_init
#define __NR_fanotify_init 323
#endif
#ifndef __NR_fanotify_mark
#define __NR_fanotify_mark 324
#endif
#ifndef __NR_fgetxattr
#define __NR_fgetxattr 214
#endif
#ifndef __NR_flistxattr
#define __NR_flistxattr 217
#endif
#ifndef __NR_fremovexattr
#define __NR_fremovexattr 220
#endif
#ifndef __NR_fsetxattr
#define __NR_fsetxattr 211
#endif
#ifndef __NR_futex
#define __NR_futex 221
#endif
#ifndef __NR_futex_waitv
#define __NR_futex_waitv 449
#endif
#ifndef __NR_get_robust_list
#define __NR_get_robust_list 299
#endif
#ifndef __NR_getpeername
#define __NR_getpeername 332
#endif
#ifndef __NR_getsockname
#define __NR_getsockname 331
#endif
#ifndef __NR_getsockopt
#define __NR_getsockopt 340
#endif
#ifndef __NR_getxattr
#define __NR_getxattr 212
#endif
#ifndef __NR_inotify_add_watch
#define __NR_inotify_add_watch 276
#endif
#ifndef __NR_inotify_init
#define __NR_inotify_init 275
#endif
#ifndef __NR_inotify_init1
#define __NR_inotify_init1 318
#endif
#ifndef __NR_inotify_rm_watch
#define __NR_inotify_rm_watch 277
#endif
#ifndef __NR_io_cancel
#define __NR_io_cancel 231
#endif
#ifndef __NR_io_destroy
#define __NR_io_destroy 228
#endif
#ifndef __NR_io_getevents
#define __NR_io_getevents 229
#endif
#ifndef __NR_io_pgetevents
#define __NR_io_pgetevents 388
#endif
#ifndef __NR_io_setup
#define __NR_io_setup 227
#endif
#ifndef __NR_io_submit
#define __NR_io_submit 230
#endif
#ifndef __NR_io_uring_enter
#define __NR_io_uring_enter 426
#endif
#ifndef __NR_io_uring_register
#define __NR_io_uring_register 427
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif
#ifndef __NR_ioctl
#define __NR_ioctl 54
#endif
#ifndef __NR_keyctl
#define __NR_keyctl 271
#endif
#ifndef __NR_landlock_add_rule
#define __NR_landlock_add_rule 445
#endif
#ifndef __NR_landlock_create_ruleset
#define __NR_landlock_create_ruleset 444
#endif
#ifndef __NR_landlock_restrict_self
#define __NR_landlock_restrict_self 446
#endif
#ifndef __NR_lgetxattr
#define __NR_lgetxattr 213
#endif
#ifndef __NR_listen
#define __NR_listen 329
#endif
#ifndef __NR_listxattr
#define __NR_listxattr 215
#endif
#ifndef __NR_llistxattr
#define __NR_llistxattr 216
#endif
#ifndef __NR_lremovexattr
#define __NR_lremovexattr 219
#endif
#ifndef __NR_lsetxattr
#define __NR_lsetxattr 210
#endif
#ifndef __NR_mkdirat
#define __NR_mkdirat 287
#endif
#ifndef __NR_mmap
#define __NR_mmap 90
#endif
#ifndef __NR_mount
#define __NR_mount 21
#endif
#ifndef __NR_msgctl
#define __NR_msgctl 402
#endif
#ifndef __NR_msgget
#define __NR_msgget 399
#endif
#ifndef __NR_msgrcv
#define __NR_msgrcv 401
#endif
#ifndef __NR_msgsnd
#define __NR_msgsnd 400
#endif
#ifndef __NR_openat
#define __NR_openat 286
#endif
#ifndef __NR_perf_event_open
#define __NR_perf_event_open 319
#endif
#ifndef __NR_pipe2
#define __NR_pipe2 317
#endif
#ifndef __NR_prctl
#define __NR_prctl 171
#endif
#ifndef __NR_read
#define __NR_read 3
#endif
#ifndef __NR_recvfrom
#define __NR_recvfrom 337
#endif
#ifndef __NR_recvmmsg
#define __NR_recvmmsg 343
#endif
#ifndef __NR_recvmsg
#define __NR_recvmsg 342
#endif
#ifndef __NR_removexattr
#define __NR_removexattr 218
#endif
#ifndef __NR_request_key
#define __NR_request_key 270
#endif
#ifndef __NR_seccomp
#define __NR_seccomp 358
#endif
#ifndef __NR_semctl
#define __NR_semctl 394
#endif
#ifndef __NR_semget
#define __NR_semget 393
#endif
#ifndef __NR_semtimedop
#define __NR_semtimedop 392
#endif
#ifndef __NR_sendmmsg
#define __NR_sendmmsg 349
#endif
#ifndef __NR_sendmsg
#define __NR_sendmsg 341
#endif
#ifndef __NR_sendto
#define __NR_sendto 335
#endif
#ifndef __NR_set_robust_list
#define __NR_set_robust_list 300
#endif
#ifndef __NR_setns
#define __NR_setns 350
#endif
#ifndef __NR_setsockopt
#define __NR_setsockopt 339
#endif
#ifndef __NR_setxattr
#define __NR_setxattr 209
#endif
#ifndef __NR_shmat
#define __NR_shmat 397
#endif
#ifndef __NR_shmctl
#define __NR_shmctl 396
#endif
#ifndef __NR_shmdt
#define __NR_shmdt 398
#endif
#ifndef __NR_shmget
#define __NR_shmget 395
#endif
#ifndef __NR_shutdown
#define __NR_shutdown 338
#endif
#ifndef __NR_socket
#define __NR_socket 326
#endif
#ifndef __NR_socketpair
#define __NR_socketpair 333
#endif
#ifndef __NR_unlinkat
#define __NR_unlinkat 292
#endif
#ifndef __NR_unshare
#define __NR_unshare 282
#endif
#ifndef __NR_userfaultfd
#define __NR_userfaultfd 364
#endif
#ifndef __NR_write
#define __NR_write 4
#endif
#endif

#if GOARCH_riscv64
#define GOARCH "riscv64"
#define SYZ_REVISION "11fc6f9e29be223be215aca7869848ae62832c23"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef __NR_accept
#define __NR_accept 202
#endif
#ifndef __NR_accept4
#define __NR_accept4 242
#endif
#ifndef __NR_add_key
#define __NR_add_key 217
#endif
#ifndef __NR_bind
#define __NR_bind 200
#endif
#ifndef __NR_bpf
#define __NR_bpf 280
#endif
#ifndef __NR_close
#define __NR_close 57
#endif
#ifndef __NR_connect
#define __NR_connect 203
#endif
#ifndef __NR_execve
#define __NR_execve 221
#endif
#ifndef __NR_execveat
#define __NR_execveat 281
#endif
#ifndef __NR_fanotify_init
#define __NR_fanotify_init 262
#endif
#ifndef __NR_fanotify_mark
#define __NR_fanotify_mark 263
#endif
#ifndef __NR_fgetxattr
#define __NR_fgetxattr 10
#endif
#ifndef __NR_flistxattr
#define __NR_flistxattr 13
#endif
#ifndef __NR_fremovexattr
#define __NR_fremovexattr 16
#endif
#ifndef __NR_fsetxattr
#define __NR_fsetxattr 7
#endif
#ifndef __NR_futex
#define __NR_futex 98
#endif
#ifndef __NR_futex_waitv
#define __NR_futex_waitv 449
#endif
#ifndef __NR_get_robust_list
#define __NR_get_robust_list 100
#endif
#ifndef __NR_getpeername
#define __NR_getpeername 205
#endif
#ifndef __NR_getsockname
#define __NR_getsockname 204
#endif
#ifndef __NR_getsockopt
#define __NR_getsockopt 209
#endif
#ifndef __NR_getxattr
#define __NR_getxattr 8
#endif
#ifndef __NR_inotify_add_watch
#define __NR_inotify_add_watch 27
#endif
#ifndef __NR_inotify_init1
#define __NR_inotify_init1 26
#endif
#ifndef __NR_inotify_rm_watch
#define __NR_inotify_rm_watch 28
#endif
#ifndef __NR_io_cancel
#define __NR_io_cancel 3
#endif
#ifndef __NR_io_destroy
#define __NR_io_destroy 1
#endif
#ifndef __NR_io_getevents
#define __NR_io_getevents 4
#endif
#ifndef __NR_io_pgetevents
#define __NR_io_pgetevents 292
#endif
#ifndef __NR_io_setup
#define __NR_io_setup 0
#endif
#ifndef __NR_io_submit
#define __NR_io_submit 2
#endif
#ifndef __NR_io_uring_enter
#define __NR_io_uring_enter 426
#endif
#ifndef __NR_io_uring_register
#define __NR_io_uring_register 427
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif
#ifndef __NR_ioctl
#define __NR_ioctl 29
#endif
#ifndef __NR_keyctl
#define __NR_keyctl 219
#endif
#ifndef __NR_landlock_add_rule
#define __NR_landlock_add_rule 445
#endif
#ifndef __NR_landlock_create_ruleset
#define __NR_landlock_create_ruleset 444
#endif
#ifndef __NR_landlock_restrict_self
#define __NR_landlock_restrict_self 446
#endif
#ifndef __NR_lgetxattr
#define __NR_lgetxattr 9
#endif
#ifndef __NR_listen
#define __NR_listen 201
#endif
#ifndef __NR_listxattr
#define __NR_listxattr 11
#endif
#ifndef __NR_llistxattr
#define __NR_llistxattr 12
#endif
#ifndef __NR_lremovexattr
#define __NR_lremovexattr 15
#endif
#ifndef __NR_lsetxattr
#define __NR_lsetxattr 6
#endif
#ifndef __NR_mkdirat
#define __NR_mkdirat 34
#endif
#ifndef __NR_mmap
#define __NR_mmap 222
#endif
#ifndef __NR_mount
#define __NR_mount 40
#endif
#ifndef __NR_msgctl
#define __NR_msgctl 187
#endif
#ifndef __NR_msgget
#define __NR_msgget 186
#endif
#ifndef __NR_msgrcv
#define __NR_msgrcv 188
#endif
#ifndef __NR_msgsnd
#define __NR_msgsnd 189
#endif
#ifndef __NR_openat
#define __NR_openat 56
#endif
#ifndef __NR_perf_event_open
#define __NR_perf_event_open 241
#endif
#ifndef __NR_pipe2
#define __NR_pipe2 59
#endif
#ifndef __NR_prctl
#define __NR_prctl 167
#endif
#ifndef __NR_read
#define __NR_read 63
#endif
#ifndef __NR_recvfrom
#define __NR_recvfrom 207
#endif
#ifndef __NR_recvmmsg
#define __NR_recvmmsg 243
#endif
#ifndef __NR_recvmsg
#define __NR_recvmsg 212
#endif
#ifndef __NR_removexattr
#define __NR_removexattr 14
#endif
#ifndef __NR_request_key
#define __NR_request_key 218
#endif
#ifndef __NR_seccomp
#define __NR_seccomp 277
#endif
#ifndef __NR_semctl
#define __NR_semctl 191
#endif
#ifndef __NR_semget
#define __NR_semget 190
#endif
#ifndef __NR_semop
#define __NR_semop 193
#endif
#ifndef __NR_semtimedop
#define __NR_semtimedop 192
#endif
#ifndef __NR_sendmmsg
#define __NR_sendmmsg 269
#endif
#ifndef __NR_sendmsg
#define __NR_sendmsg 211
#endif
#ifndef __NR_sendto
#define __NR_sendto 206
#endif
#ifndef __NR_set_robust_list
#define __NR_set_robust_list 99
#endif
#ifndef __NR_setns
#define __NR_setns 268
#endif
#ifndef __NR_setsockopt
#define __NR_setsockopt 208
#endif
#ifndef __NR_setxattr
#define __NR_setxattr 5
#endif
#ifndef __NR_shmat
#define __NR_shmat 196
#endif
#ifndef __NR_shmctl
#define __NR_shmctl 195
#endif
#ifndef __NR_shmdt
#define __NR_shmdt 197
#endif
#ifndef __NR_shmget
#define __NR_shmget 194
#endif
#ifndef __NR_shutdown
#define __NR_shutdown 210
#endif
#ifndef __NR_socket
#define __NR_socket 198
#endif
#ifndef __NR_socketpair
#define __NR_socketpair 199
#endif
#ifndef __NR_unlinkat
#define __NR_unlinkat 35
#endif
#ifndef __NR_unshare
#define __NR_unshare 97
#endif
#ifndef __NR_userfaultfd
#define __NR_userfaultfd 282
#endif
#ifndef __NR_write
#define __NR_write 64
#endif
#endif

#if GOARCH_s390x
#define GOARCH "s390x"
#define SYZ_REVISION "fed8c205ed8a50cb7e3194b9d52ec85eadb08e63"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 4294963200
#ifndef __NR_accept4
#define __NR_accept4 364
#endif
#ifndef __NR_add_key
#define __NR_add_key 278
#endif
#ifndef __NR_bind
#define __NR_bind 361
#endif
#ifndef __NR_bpf
#define __NR_bpf 351
#endif
#ifndef __NR_close
#define __NR_close 6
#endif
#ifndef __NR_connect
#define __NR_connect 362
#endif
#ifndef __NR_execve
#define __NR_execve 11
#endif
#ifndef __NR_execveat
#define __NR_execveat 354
#endif
#ifndef __NR_fanotify_init
#define __NR_fanotify_init 332
#endif
#ifndef __NR_fanotify_mark
#define __NR_fanotify_mark 333
#endif
#ifndef __NR_fgetxattr
#define __NR_fgetxattr 229
#endif
#ifndef __NR_flistxattr
#define __NR_flistxattr 232
#endif
#ifndef __NR_fremovexattr
#define __NR_fremovexattr 235
#endif
#ifndef __NR_fsetxattr
#define __NR_fsetxattr 226
#endif
#ifndef __NR_futex
#define __NR_futex 238
#endif
#ifndef __NR_futex_waitv
#define __NR_futex_waitv 449
#endif
#ifndef __NR_get_robust_list
#define __NR_get_robust_list 305
#endif
#ifndef __NR_getpeername
#define __NR_getpeername 368
#endif
#ifndef __NR_getsockname
#define __NR_getsockname 367
#endif
#ifndef __NR_getsockopt
#define __NR_getsockopt 365
#endif
#ifndef __NR_getxattr
#define __NR_getxattr 227
#endif
#ifndef __NR_inotify_add_watch
#define __NR_inotify_add_watch 285
#endif
#ifndef __NR_inotify_init
#define __NR_inotify_init 284
#endif
#ifndef __NR_inotify_init1
#define __NR_inotify_init1 324
#endif
#ifndef __NR_inotify_rm_watch
#define __NR_inotify_rm_watch 286
#endif
#ifndef __NR_io_cancel
#define __NR_io_cancel 247
#endif
#ifndef __NR_io_destroy
#define __NR_io_destroy 244
#endif
#ifndef __NR_io_getevents
#define __NR_io_getevents 245
#endif
#ifndef __NR_io_pgetevents
#define __NR_io_pgetevents 382
#endif
#ifndef __NR_io_setup
#define __NR_io_setup 243
#endif
#ifndef __NR_io_submit
#define __NR_io_submit 246
#endif
#ifndef __NR_io_uring_enter
#define __NR_io_uring_enter 426
#endif
#ifndef __NR_io_uring_register
#define __NR_io_uring_register 427
#endif
#ifndef __NR_io_uring_setup
#define __NR_io_uring_setup 425
#endif
#ifndef __NR_ioctl
#define __NR_ioctl 54
#endif
#ifndef __NR_keyctl
#define __NR_keyctl 280
#endif
#ifndef __NR_landlock_add_rule
#define __NR_landlock_add_rule 445
#endif
#ifndef __NR_landlock_create_ruleset
#define __NR_landlock_create_ruleset 444
#endif
#ifndef __NR_landlock_restrict_self
#define __NR_landlock_restrict_self 446
#endif
#ifndef __NR_lgetxattr
#define __NR_lgetxattr 228
#endif
#ifndef __NR_listen
#define __NR_listen 363
#endif
#ifndef __NR_listxattr
#define __NR_listxattr 230
#endif
#ifndef __NR_llistxattr
#define __NR_llistxattr 231
#endif
#ifndef __NR_lremovexattr
#define __NR_lremovexattr 234
#endif
#ifndef __NR_lsetxattr
#define __NR_lsetxattr 225
#endif
#ifndef __NR_mkdirat
#define __NR_mkdirat 289
#endif
#ifndef __NR_mmap
#define __NR_mmap 90
#endif
#ifndef __NR_mount
#define __NR_mount 21
#endif
#ifndef __NR_msgctl
#define __NR_msgctl 402
#endif
#ifndef __NR_msgget
#define __NR_msgget 399
#endif
#ifndef __NR_msgrcv
#define __NR_msgrcv 401
#endif
#ifndef __NR_msgsnd
#define __NR_msgsnd 400
#endif
#ifndef __NR_openat
#define __NR_openat 288
#endif
#ifndef __NR_perf_event_open
#define __NR_perf_event_open 331
#endif
#ifndef __NR_pipe2
#define __NR_pipe2 325
#endif
#ifndef __NR_prctl
#define __NR_prctl 172
#endif
#ifndef __NR_read
#define __NR_read 3
#endif
#ifndef __NR_recvfrom
#define __NR_recvfrom 371
#endif
#ifndef __NR_recvmmsg
#define __NR_recvmmsg 357
#endif
#ifndef __NR_recvmsg
#define __NR_recvmsg 372
#endif
#ifndef __NR_removexattr
#define __NR_removexattr 233
#endif
#ifndef __NR_request_key
#define __NR_request_key 279
#endif
#ifndef __NR_seccomp
#define __NR_seccomp 348
#endif
#ifndef __NR_semctl
#define __NR_semctl 394
#endif
#ifndef __NR_semget
#define __NR_semget 393
#endif
#ifndef __NR_semtimedop
#define __NR_semtimedop 392
#endif
#ifndef __NR_sendmmsg
#define __NR_sendmmsg 358
#endif
#ifndef __NR_sendmsg
#define __NR_sendmsg 370
#endif
#ifndef __NR_sendto
#define __NR_sendto 369
#endif
#ifndef __NR_set_robust_list
#define __NR_set_robust_list 304
#endif
#ifndef __NR_setns
#define __NR_setns 339
#endif
#ifndef __NR_setsockopt
#define __NR_setsockopt 366
#endif
#ifndef __NR_setxattr
#define __NR_setxattr 224
#endif
#ifndef __NR_shmat
#define __NR_shmat 397
#endif
#ifndef __NR_shmctl
#define __NR_shmctl 396
#endif
#ifndef __NR_shmdt
#define __NR_shmdt 398
#endif
#ifndef __NR_shmget
#define __NR_shmget 395
#endif
#ifndef __NR_shutdown
#define __NR_shutdown 373
#endif
#ifndef __NR_socket
#define __NR_socket 359
#endif
#ifndef __NR_socketpair
#define __NR_socketpair 360
#endif
#ifndef __NR_unlinkat
#define __NR_unlinkat 294
#endif
#ifndef __NR_unshare
#define __NR_unshare 303
#endif
#ifndef __NR_userfaultfd
#define __NR_userfaultfd 355
#endif
#ifndef __NR_write
#define __NR_write 4
#endif
#endif

#endif

#if GOOS_netbsd
#define GOOS "netbsd"

#if GOARCH_amd64
#define GOARCH "amd64"
#define SYZ_REVISION "6b3561a0992840cbae76a19c7276e9e2f08a8d4b"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef SYS___clock_getres50
#define SYS___clock_getres50 429
#endif
#ifndef SYS___clock_gettime50
#define SYS___clock_gettime50 427
#endif
#ifndef SYS___clock_settime50
#define SYS___clock_settime50 428
#endif
#ifndef SYS___clone
#define SYS___clone 287
#endif
#ifndef SYS___fhopen40
#define SYS___fhopen40 396
#endif
#ifndef SYS___fhstat50
#define SYS___fhstat50 451
#endif
#ifndef SYS___fhstatvfs190
#define SYS___fhstatvfs190 486
#endif
#ifndef SYS___fstat50
#define SYS___fstat50 440
#endif
#ifndef SYS___futimes50
#define SYS___futimes50 423
#endif
#ifndef SYS___getcwd
#define SYS___getcwd 296
#endif
#ifndef SYS___getdents30
#define SYS___getdents30 390
#endif
#ifndef SYS___getfh30
#define SYS___getfh30 395
#endif
#ifndef SYS___getitimer50
#define SYS___getitimer50 426
#endif
#ifndef SYS___getlogin
#define SYS___getlogin 49
#endif
#ifndef SYS___getrusage50
#define SYS___getrusage50 445
#endif
#ifndef SYS___getvfsstat90
#define SYS___getvfsstat90 483
#endif
#ifndef SYS___lstat50
#define SYS___lstat50 441
#endif
#ifndef SYS___lutimes50
#define SYS___lutimes50 424
#endif
#ifndef SYS___mount50
#define SYS___mount50 410
#endif
#ifndef SYS___msync13
#define SYS___msync13 277
#endif
#ifndef SYS___nanosleep50
#define SYS___nanosleep50 430
#endif
#ifndef SYS___posix_chown
#define SYS___posix_chown 283
#endif
#ifndef SYS___posix_fadvise50
#define SYS___posix_fadvise50 416
#endif
#ifndef SYS___posix_fchown
#define SYS___posix_fchown 284
#endif
#ifndef SYS___posix_lchown
#define SYS___posix_lchown 285
#endif
#ifndef SYS___posix_rename
#define SYS___posix_rename 270
#endif
#ifndef SYS___select50
#define SYS___select50 417
#endif
#ifndef SYS___setitimer50
#define SYS___setitimer50 425
#endif
#ifndef SYS___stat50
#define SYS___stat50 439
#endif
#ifndef SYS___utimes50
#define SYS___utimes50 420
#endif
#ifndef SYS___vfork14
#define SYS___vfork14 282
#endif
#ifndef SYS___wait450
#define SYS___wait450 449
#endif
#ifndef SYS__ksem_close
#define SYS__ksem_close 250
#endif
#ifndef SYS__ksem_destroy
#define SYS__ksem_destroy 255
#endif
#ifndef SYS__ksem_getvalue
#define SYS__ksem_getvalue 254
#endif
#ifndef SYS__ksem_init
#define SYS__ksem_init 247
#endif
#ifndef SYS__ksem_open
#define SYS__ksem_open 248
#endif
#ifndef SYS__ksem_post
#define SYS__ksem_post 251
#endif
#ifndef SYS__ksem_timedwait
#define SYS__ksem_timedwait 256
#endif
#ifndef SYS__ksem_trywait
#define SYS__ksem_trywait 253
#endif
#ifndef SYS__ksem_unlink
#define SYS__ksem_unlink 249
#endif
#ifndef SYS__ksem_wait
#define SYS__ksem_wait 252
#endif
#ifndef SYS__lwp_continue
#define SYS__lwp_continue 314
#endif
#ifndef SYS__lwp_create
#define SYS__lwp_create 309
#endif
#ifndef SYS__lwp_ctl
#define SYS__lwp_ctl 325
#endif
#ifndef SYS__lwp_detach
#define SYS__lwp_detach 319
#endif
#ifndef SYS__lwp_exit
#define SYS__lwp_exit 310
#endif
#ifndef SYS__lwp_getname
#define SYS__lwp_getname 324
#endif
#ifndef SYS__lwp_getprivate
#define SYS__lwp_getprivate 316
#endif
#ifndef SYS__lwp_kill
#define SYS__lwp_kill 318
#endif
#ifndef SYS__lwp_self
#define SYS__lwp_self 311
#endif
#ifndef SYS__lwp_setname
#define SYS__lwp_setname 323
#endif
#ifndef SYS__lwp_setprivate
#define SYS__lwp_setprivate 317
#endif
#ifndef SYS__lwp_suspend
#define SYS__lwp_suspend 313
#endif
#ifndef SYS__lwp_unpark
#define SYS__lwp_unpark 321
#endif
#ifndef SYS__lwp_unpark_all
#define SYS__lwp_unpark_all 322
#endif
#ifndef SYS__lwp_wait
#define SYS__lwp_wait 312
#endif
#ifndef SYS__lwp_wakeup
#define SYS__lwp_wakeup 315
#endif
#ifndef SYS_accept
#define SYS_accept 30
#endif
#ifndef SYS_access
#define SYS_access 33
#endif
#ifndef SYS_acct
#define SYS_acct 51
#endif
#ifndef SYS_bind
#define SYS_bind 104
#endif
#ifndef SYS_chdir
#define SYS_chdir 12
#endif
#ifndef SYS_chflags
#define SYS_chflags 34
#endif
#ifndef SYS_chmod
#define SYS_chmod 15
#endif
#ifndef SYS_chown
#define SYS_chown 16
#endif
#ifndef SYS_chroot
#define SYS_chroot 61
#endif
#ifndef SYS_clock_nanosleep
#define SYS_clock_nanosleep 477
#endif
#ifndef SYS_close
#define SYS_close 6
#endif
#ifndef SYS_compat_09_ogetdomainname
#define SYS_compat_09_ogetdomainname 162
#endif
#ifndef SYS_compat_09_osetdomainname
#define SYS_compat_09_osetdomainname 163
#endif
#ifndef SYS_compat_09_ouname
#define SYS_compat_09_ouname 164
#endif
#ifndef SYS_compat_12_fstat12
#define SYS_compat_12_fstat12 189
#endif
#ifndef SYS_compat_12_getdirentries
#define SYS_compat_12_getdirentries 196
#endif
#ifndef SYS_compat_12_lstat12
#define SYS_compat_12_lstat12 190
#endif
#ifndef SYS_compat_12_msync
#define SYS_compat_12_msync 65
#endif
#ifndef SYS_compat_12_stat12
#define SYS_compat_12_stat12 188
#endif
#ifndef SYS_compat_20_fstatfs
#define SYS_compat_20_fstatfs 158
#endif
#ifndef SYS_compat_20_getfsstat
#define SYS_compat_20_getfsstat 18
#endif
#ifndef SYS_compat_20_statfs
#define SYS_compat_20_statfs 157
#endif
#ifndef SYS_compat_30___fhstat30
#define SYS_compat_30___fhstat30 392
#endif
#ifndef SYS_compat_30___fstat13
#define SYS_compat_30___fstat13 279
#endif
#ifndef SYS_compat_30___lstat13
#define SYS_compat_30___lstat13 280
#endif
#ifndef SYS_compat_30___stat13
#define SYS_compat_30___stat13 278
#endif
#ifndef SYS_compat_30_fhopen
#define SYS_compat_30_fhopen 298
#endif
#ifndef SYS_compat_30_fhstat
#define SYS_compat_30_fhstat 299
#endif
#ifndef SYS_compat_30_fhstatvfs1
#define SYS_compat_30_fhstatvfs1 359
#endif
#ifndef SYS_compat_30_getdents
#define SYS_compat_30_getdents 272
#endif
#ifndef SYS_compat_30_getfh
#define SYS_compat_30_getfh 161
#endif
#ifndef SYS_compat_30_socket
#define SYS_compat_30_socket 97
#endif
#ifndef SYS_compat_40_mount
#define SYS_compat_40_mount 21
#endif
#ifndef SYS_compat_43_fstat43
#define SYS_compat_43_fstat43 62
#endif
#ifndef SYS_compat_43_lstat43
#define SYS_compat_43_lstat43 40
#endif
#ifndef SYS_compat_43_oaccept
#define SYS_compat_43_oaccept 99
#endif
#ifndef SYS_compat_43_ocreat
#define SYS_compat_43_ocreat 8
#endif
#ifndef SYS_compat_43_oftruncate
#define SYS_compat_43_oftruncate 130
#endif
#ifndef SYS_compat_43_ogetdirentries
#define SYS_compat_43_ogetdirentries 156
#endif
#ifndef SYS_compat_43_ogethostid
#define SYS_compat_43_ogethostid 142
#endif
#ifndef SYS_compat_43_ogethostname
#define SYS_compat_43_ogethostname 87
#endif
#ifndef SYS_compat_43_ogetpeername
#define SYS_compat_43_ogetpeername 141
#endif
#ifndef SYS_compat_43_ogetrlimit
#define SYS_compat_43_ogetrlimit 144
#endif
#ifndef SYS_compat_43_ogetsockname
#define SYS_compat_43_ogetsockname 150
#endif
#ifndef SYS_compat_43_olseek
#define SYS_compat_43_olseek 19
#endif
#ifndef SYS_compat_43_ommap
#define SYS_compat_43_ommap 71
#endif
#ifndef SYS_compat_43_orecv
#define SYS_compat_43_orecv 102
#endif
#ifndef SYS_compat_43_orecvfrom
#define SYS_compat_43_orecvfrom 125
#endif
#ifndef SYS_compat_43_orecvmsg
#define SYS_compat_43_orecvmsg 113
#endif
#ifndef SYS_compat_43_osend
#define SYS_compat_43_osend 101
#endif
#ifndef SYS_compat_43_osendmsg
#define SYS_compat_43_osendmsg 114
#endif
#ifndef SYS_compat_43_osethostid
#define SYS_compat_43_osethostid 143
#endif
#ifndef SYS_compat_43_osethostname
#define SYS_compat_43_osethostname 88
#endif
#ifndef SYS_compat_43_osetrlimit
#define SYS_compat_43_osetrlimit 145
#endif
#ifndef SYS_compat_43_otruncate
#define SYS_compat_43_otruncate 129
#endif
#ifndef SYS_compat_43_stat43
#define SYS_compat_43_stat43 38
#endif
#ifndef SYS_compat_50___fstat30
#define SYS_compat_50___fstat30 388
#endif
#ifndef SYS_compat_50___lstat30
#define SYS_compat_50___lstat30 389
#endif
#ifndef SYS_compat_50___stat30
#define SYS_compat_50___stat30 387
#endif
#ifndef SYS_compat_50__lwp_park
#define SYS_compat_50__lwp_park 320
#endif
#ifndef SYS_compat_50_clock_getres
#define SYS_compat_50_clock_getres 234
#endif
#ifndef SYS_compat_50_clock_gettime
#define SYS_compat_50_clock_gettime 232
#endif
#ifndef SYS_compat_50_clock_settime
#define SYS_compat_50_clock_settime 233
#endif
#ifndef SYS_compat_50_futimes
#define SYS_compat_50_futimes 206
#endif
#ifndef SYS_compat_50_getitimer
#define SYS_compat_50_getitimer 86
#endif
#ifndef SYS_compat_50_getrusage
#define SYS_compat_50_getrusage 117
#endif
#ifndef SYS_compat_50_lutimes
#define SYS_compat_50_lutimes 276
#endif
#ifndef SYS_compat_50_mknod
#define SYS_compat_50_mknod 14
#endif
#ifndef SYS_compat_50_nanosleep
#define SYS_compat_50_nanosleep 240
#endif
#ifndef SYS_compat_50_quotactl
#define SYS_compat_50_quotactl 148
#endif
#ifndef SYS_compat_50_select
#define SYS_compat_50_select 93
#endif
#ifndef SYS_compat_50_setitimer
#define SYS_compat_50_setitimer 83
#endif
#ifndef SYS_compat_50_utimes
#define SYS_compat_50_utimes 138
#endif
#ifndef SYS_compat_50_wait4
#define SYS_compat_50_wait4 7
#endif
#ifndef SYS_compat_60__lwp_park
#define SYS_compat_60__lwp_park 434
#endif
#ifndef SYS_compat_90_fhstatvfs1
#define SYS_compat_90_fhstatvfs1 397
#endif
#ifndef SYS_compat_90_fstatvfs1
#define SYS_compat_90_fstatvfs1 358
#endif
#ifndef SYS_compat_90_getvfsstat
#define SYS_compat_90_getvfsstat 356
#endif
#ifndef SYS_compat_90_statvfs1
#define SYS_compat_90_statvfs1 357
#endif
#ifndef SYS_connect
#define SYS_connect 98
#endif
#ifndef SYS_dup
#define SYS_dup 41
#endif
#ifndef SYS_dup2
#define SYS_dup2 90
#endif
#ifndef SYS_dup3
#define SYS_dup3 454
#endif
#ifndef SYS_execve
#define SYS_execve 59
#endif
#ifndef SYS_exit
#define SYS_exit 1
#endif
#ifndef SYS_faccessat
#define SYS_faccessat 462
#endif
#ifndef SYS_fchdir
#define SYS_fchdir 13
#endif
#ifndef SYS_fchflags
#define SYS_fchflags 35
#endif
#ifndef SYS_fchmod
#define SYS_fchmod 124
#endif
#ifndef SYS_fchmodat
#define SYS_fchmodat 463
#endif
#ifndef SYS_fchown
#define SYS_fchown 123
#endif
#ifndef SYS_fchownat
#define SYS_fchownat 464
#endif
#ifndef SYS_fchroot
#define SYS_fchroot 297
#endif
#ifndef SYS_fcntl
#define SYS_fcntl 92
#endif
#ifndef SYS_fdatasync
#define SYS_fdatasync 241
#endif
#ifndef SYS_fktrace
#define SYS_fktrace 288
#endif
#ifndef SYS_flock
#define SYS_flock 131
#endif
#ifndef SYS_fork
#define SYS_fork 2
#endif
#ifndef SYS_fpathconf
#define SYS_fpathconf 192
#endif
#ifndef SYS_fstatat
#define SYS_fstatat 466
#endif
#ifndef SYS_fsync
#define SYS_fsync 95
#endif
#ifndef SYS_ftruncate
#define SYS_ftruncate 201
#endif
#ifndef SYS_getegid
#define SYS_getegid 43
#endif
#ifndef SYS_geteuid
#define SYS_geteuid 25
#endif
#ifndef SYS_getgid
#define SYS_getgid 47
#endif
#ifndef SYS_getgroups
#define SYS_getgroups 79
#endif
#ifndef SYS_getpeername
#define SYS_getpeername 31
#endif
#ifndef SYS_getpgid
#define SYS_getpgid 207
#endif
#ifndef SYS_getpgrp
#define SYS_getpgrp 81
#endif
#ifndef SYS_getpid
#define SYS_getpid 20
#endif
#ifndef SYS_getppid
#define SYS_getppid 39
#endif
#ifndef SYS_getpriority
#define SYS_getpriority 100
#endif
#ifndef SYS_getrlimit
#define SYS_getrlimit 194
#endif
#ifndef SYS_getsid
#define SYS_getsid 286
#endif
#ifndef SYS_getsockname
#define SYS_getsockname 32
#endif
#ifndef SYS_getsockopt
#define SYS_getsockopt 118
#endif
#ifndef SYS_getuid
#define SYS_getuid 24
#endif
#ifndef SYS_ioctl
#define SYS_ioctl 54
#endif
#ifndef SYS_ktrace
#define SYS_ktrace 45
#endif
#ifndef SYS_lchflags
#define SYS_lchflags 304
#endif
#ifndef SYS_lchmod
#define SYS_lchmod 274
#endif
#ifndef SYS_lchown
#define SYS_lchown 275
#endif
#ifndef SYS_link
#define SYS_link 9
#endif
#ifndef SYS_linkat
#define SYS_linkat 457
#endif
#ifndef SYS_listen
#define SYS_listen 106
#endif
#ifndef SYS_lseek
#define SYS_lseek 199
#endif
#ifndef SYS_madvise
#define SYS_madvise 75
#endif
#ifndef SYS_mincore
#define SYS_mincore 78
#endif
#ifndef SYS_minherit
#define SYS_minherit 273
#endif
#ifndef SYS_mkdir
#define SYS_mkdir 136
#endif
#ifndef SYS_mkdirat
#define SYS_mkdirat 461
#endif
#ifndef SYS_mknod
#define SYS_mknod 450
#endif
#ifndef SYS_mknodat
#define SYS_mknodat 460
#endif
#ifndef SYS_mlock
#define SYS_mlock 203
#endif
#ifndef SYS_mlockall
#define SYS_mlockall 242
#endif
#ifndef SYS_mmap
#define SYS_mmap 197
#endif
#ifndef SYS_mprotect
#define SYS_mprotect 74
#endif
#ifndef SYS_msgctl
#define SYS_msgctl 444
#endif
#ifndef SYS_msgget
#define SYS_msgget 225
#endif
#ifndef SYS_msgrcv
#define SYS_msgrcv 227
#endif
#ifndef SYS_msgsnd
#define SYS_msgsnd 226
#endif
#ifndef SYS_munlock
#define SYS_munlock 204
#endif
#ifndef SYS_munlockall
#define SYS_munlockall 243
#endif
#ifndef SYS_munmap
#define SYS_munmap 73
#endif
#ifndef SYS_open
#define SYS_open 5
#endif
#ifndef SYS_openat
#define SYS_openat 468
#endif
#ifndef SYS_paccept
#define SYS_paccept 456
#endif
#ifndef SYS_pathconf
#define SYS_pathconf 191
#endif
#ifndef SYS_pipe
#define SYS_pipe 42
#endif
#ifndef SYS_pipe2
#define SYS_pipe2 453
#endif
#ifndef SYS_poll
#define SYS_poll 209
#endif
#ifndef SYS_posix_spawn
#define SYS_posix_spawn 474
#endif
#ifndef SYS_pread
#define SYS_pread 173
#endif
#ifndef SYS_preadv
#define SYS_preadv 289
#endif
#ifndef SYS_profil
#define SYS_profil 44
#endif
#ifndef SYS_ptrace
#define SYS_ptrace 26
#endif
#ifndef SYS_pwrite
#define SYS_pwrite 174
#endif
#ifndef SYS_pwritev
#define SYS_pwritev 290
#endif
#ifndef SYS_read
#define SYS_read 3
#endif
#ifndef SYS_readlink
#define SYS_readlink 58
#endif
#ifndef SYS_readlinkat
#define SYS_readlinkat 469
#endif
#ifndef SYS_readv
#define SYS_readv 120
#endif
#ifndef SYS_recvfrom
#define SYS_recvfrom 29
#endif
#ifndef SYS_recvmmsg
#define SYS_recvmmsg 475
#endif
#ifndef SYS_recvmsg
#define SYS_recvmsg 27
#endif
#ifndef SYS_rename
#define SYS_rename 128
#endif
#ifndef SYS_renameat
#define SYS_renameat 458
#endif
#ifndef SYS_rmdir
#define SYS_rmdir 137
#endif
#ifndef SYS_semctl
#define SYS_semctl 442
#endif
#ifndef SYS_semget
#define SYS_semget 221
#endif
#ifndef SYS_semop
#define SYS_semop 222
#endif
#ifndef SYS_sendmmsg
#define SYS_sendmmsg 476
#endif
#ifndef SYS_sendmsg
#define SYS_sendmsg 28
#endif
#ifndef SYS_sendto
#define SYS_sendto 133
#endif
#ifndef SYS_setegid
#define SYS_setegid 182
#endif
#ifndef SYS_seteuid
#define SYS_seteuid 183
#endif
#ifndef SYS_setgid
#define SYS_setgid 181
#endif
#ifndef SYS_setgroups
#define SYS_setgroups 80
#endif
#ifndef SYS_setpgid
#define SYS_setpgid 82
#endif
#ifndef SYS_setpriority
#define SYS_setpriority 96
#endif
#ifndef SYS_setregid
#define SYS_setregid 127
#endif
#ifndef SYS_setreuid
#define SYS_setreuid 126
#endif
#ifndef SYS_setrlimit
#define SYS_setrlimit 195
#endif
#ifndef SYS_setsockopt
#define SYS_setsockopt 105
#endif
#ifndef SYS_setuid
#define SYS_setuid 23
#endif
#ifndef SYS_shmat
#define SYS_shmat 228
#endif
#ifndef SYS_shmctl
#define SYS_shmctl 443
#endif
#ifndef SYS_shmdt
#define SYS_shmdt 230
#endif
#ifndef SYS_shmget
#define SYS_shmget 231
#endif
#ifndef SYS_shutdown
#define SYS_shutdown 134
#endif
#ifndef SYS_socket
#define SYS_socket 394
#endif
#ifndef SYS_socketpair
#define SYS_socketpair 135
#endif
#ifndef SYS_symlink
#define SYS_symlink 57
#endif
#ifndef SYS_symlinkat
#define SYS_symlinkat 470
#endif
#ifndef SYS_sync
#define SYS_sync 36
#endif
#ifndef SYS_truncate
#define SYS_truncate 200
#endif
#ifndef SYS_umask
#define SYS_umask 60
#endif
#ifndef SYS_undelete
#define SYS_undelete 205
#endif
#ifndef SYS_unlink
#define SYS_unlink 10
#endif
#ifndef SYS_unlinkat
#define SYS_unlinkat 471
#endif
#ifndef SYS_unmount
#define SYS_unmount 22
#endif
#ifndef SYS_utimensat
#define SYS_utimensat 467
#endif
#ifndef SYS_vfork
#define SYS_vfork 66
#endif
#ifndef SYS_write
#define SYS_write 4
#endif
#ifndef SYS_writev
#define SYS_writev 121
#endif
#endif

#endif

#if GOOS_openbsd
#define GOOS "openbsd"

#if GOARCH_amd64
#define GOARCH "amd64"
#define SYZ_REVISION "f34bb57ce1b11189197f6a99841e579ce3d7ba16"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef SYS_semctl
#define SYS_semctl 295
#endif
#endif

#endif

#if GOOS_test
#define GOOS "test"

#if GOARCH_32_fork_shmem
#define GOARCH "32_fork_shmem"
#define SYZ_REVISION "54369bc37550123341131cbd0c071c1082a335fc"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef SYS_breaks_returns
#define SYS_breaks_returns 0
#endif
#ifndef SYS_csource0
#define SYS_csource0 0
#endif
#ifndef SYS_csource1
#define SYS_csource1 0
#endif
#ifndef SYS_csource2
#define SYS_csource2 0
#endif
#ifndef SYS_csource3
#define SYS_csource3 0
#endif
#ifndef SYS_csource4
#define SYS_csource4 0
#endif
#ifndef SYS_csource5
#define SYS_csource5 0
#endif
#ifndef SYS_csource6
#define SYS_csource6 0
#endif
#ifndef SYS_disabled0
#define SYS_disabled0 0
#endif
#ifndef SYS_disabled1
#define SYS_disabled1 0
#endif
#ifndef SYS_disabled2
#define SYS_disabled2 0
#endif
#ifndef SYS_fallback
#define SYS_fallback 0
#endif
#ifndef SYS_foo
#define SYS_foo 0
#endif
#ifndef SYS_minimize
#define SYS_minimize 0
#endif
#ifndef SYS_mutate0
#define SYS_mutate0 0
#endif
#ifndef SYS_mutate1
#define SYS_mutate1 0
#endif
#ifndef SYS_mutate2
#define SYS_mutate2 0
#endif
#ifndef SYS_mutate3
#define SYS_mutate3 0
#endif
#ifndef SYS_mutate4
#define SYS_mutate4 0
#endif
#ifndef SYS_mutate5
#define SYS_mutate5 0
#endif
#ifndef SYS_mutate6
#define SYS_mutate6 0
#endif
#ifndef SYS_mutate7
#define SYS_mutate7 0
#endif
#ifndef SYS_mutate8
#define SYS_mutate8 0
#endif
#ifndef SYS_mutate_array
#define SYS_mutate_array 0
#endif
#ifndef SYS_mutate_array2
#define SYS_mutate_array2 0
#endif
#ifndef SYS_mutate_buffer
#define SYS_mutate_buffer 0
#endif
#ifndef SYS_mutate_flags
#define SYS_mutate_flags 0
#endif
#ifndef SYS_mutate_flags2
#define SYS_mutate_flags2 0
#endif
#ifndef SYS_mutate_flags3
#define SYS_mutate_flags3 0
#endif
#ifndef SYS_mutate_integer
#define SYS_mutate_integer 0
#endif
#ifndef SYS_mutate_integer2
#define SYS_mutate_integer2 0
#endif
#ifndef SYS_mutate_rangedbuffer
#define SYS_mutate_rangedbuffer 0
#endif
#ifndef SYS_mutate_union
#define SYS_mutate_union 0
#endif
#ifndef SYS_overlay_any
#define SYS_overlay_any 0
#endif
#ifndef SYS_overlay_ctor
#define SYS_overlay_ctor 0
#endif
#ifndef SYS_overlay_uses
#define SYS_overlay_uses 0
#endif
#ifndef SYS_serialize0
#define SYS_serialize0 0
#endif
#ifndef SYS_serialize1
#define SYS_serialize1 0
#endif
#ifndef SYS_test
#define SYS_test 0
#endif
#ifndef SYS_test_excessive_args1
#define SYS_test_excessive_args1 0
#endif
#ifndef SYS_test_excessive_args2
#define SYS_test_excessive_args2 0
#endif
#ifndef SYS_test_length15
#define SYS_test_length15 0
#endif
#ifndef SYS_unsupported
#define SYS_unsupported 0
#endif
#endif

#if GOARCH_32_shmem
#define GOARCH "32_shmem"
#define SYZ_REVISION "c9525423428f3be9e89b25e83ddf9247d35e0d92"
#define SYZ_EXECUTOR_USES_FORK_SERVER 0
#define SYZ_EXECUTOR_USES_SHMEM 1
#define SYZ_PAGE_SIZE 8192
#define SYZ_NUM_PAGES 2048
#define SYZ_DATA_OFFSET 536870912
#ifndef SYS_breaks_returns
#define SYS_breaks_returns 0
#endif
#ifndef SYS_csource0
#define SYS_csource0 0
#endif
#ifndef SYS_csource1
#define SYS_csource1 0
#endif
#ifndef SYS_csource2
#define SYS_csource2 0
#endif
#ifndef SYS_csource3
#define SYS_csource3 0
#endif
#ifndef SYS_csource4
#define SYS_csource4 0
#endif
#ifndef SYS_csource5
#define SYS_csource5 0
#endif
#ifndef SYS_csource6
#define SYS_csource6 0
#endif
#ifndef SYS_disabled0
#define SYS_disabled0 0
#endif
#ifndef SYS_disabled1
#define SYS_disabled1 0
#endif
#ifndef SYS_disabled2
#define SYS_disabled2 0
#endif
#ifndef SYS_fallback
#define SYS_fallback 0
#endif
#ifndef SYS_foo
#define SYS_foo 0
#endif
#ifndef SYS_minimize
#define SYS_minimize 0
#endif
#ifndef SYS_mutate0
#define SYS_mutate0 0
#endif
#ifndef SYS_mutate1
#define SYS_mutate1 0
#endif
#ifndef SYS_mutate2
#define SYS_mutate2 0
#endif
#ifndef SYS_mutate3
#define SYS_mutate3 0
#endif
#ifndef SYS_mutate4
#define SYS_mutate4 0
#endif
#ifndef SYS_mutate5
#define SYS_mutate5 0
#endif
#ifndef SYS_mutate6
#define SYS_mutate6 0
#endif
#ifndef SYS_mutate7
#define SYS_mutate7 0
#endif
#ifndef SYS_mutate8
#define SYS_mutate8 0
#endif
#ifndef SYS_mutate_array
#define SYS_mutate_array 0
#endif
#ifndef SYS_mutate_array2
#define SYS_mutate_array2 0
#endif
#ifndef SYS_mutate_buffer
#define SYS_mutate_buffer 0
#endif
#ifndef SYS_mutate_flags
#define SYS_mutate_flags 0
#endif
#ifndef SYS_mutate_flags2
#define SYS_mutate_flags2 0
#endif
#ifndef SYS_mutate_flags3
#define SYS_mutate_flags3 0
#endif
#ifndef SYS_mutate_integer
#define SYS_mutate_integer 0
#endif
#ifndef SYS_mutate_integer2
#define SYS_mutate_integer2 0
#endif
#ifndef SYS_mutate_rangedbuffer
#define SYS_mutate_rangedbuffer 0
#endif
#ifndef SYS_mutate_union
#define SYS_mutate_union 0
#endif
#ifndef SYS_overlay_any
#define SYS_overlay_any 0
#endif
#ifndef SYS_overlay_ctor
#define SYS_overlay_ctor 0
#endif
#ifndef SYS_overlay_uses
#define SYS_overlay_uses 0
#endif
#ifndef SYS_serialize0
#define SYS_serialize0 0
#endif
#ifndef SYS_serialize1
#define SYS_serialize1 0
#endif
#ifndef SYS_test
#define SYS_test 0
#endif
#ifndef SYS_test_excessive_args1
#define SYS_test_excessive_args1 0
#endif
#ifndef SYS_test_excessive_args2
#define SYS_test_excessive_args2 0
#endif
#ifndef SYS_test_length15
#define SYS_test_length15 0
#endif
#ifndef SYS_unsupported
#define SYS_unsupported 0
#endif
#endif

#if GOARCH_64
#define GOARCH "64"
#define SYZ_REVISION "2b33e791a5e3faf376b194c0ed3743aca5c61d1a"
#define SYZ_EXECUTOR_USES_FORK_SERVER 0
#define SYZ_EXECUTOR_USES_SHMEM 0
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#ifndef SYS_breaks_returns
#define SYS_breaks_returns 0
#endif
#ifndef SYS_csource0
#define SYS_csource0 0
#endif
#ifndef SYS_csource1
#define SYS_csource1 0
#endif
#ifndef SYS_csource2
#define SYS_csource2 0
#endif
#ifndef SYS_csource3
#define SYS_csource3 0
#endif
#ifndef SYS_csource4
#define SYS_csource4 0
#endif
#ifndef SYS_csource5
#define SYS_csource5 0
#endif
#ifndef SYS_csource6
#define SYS_csource6 0
#endif
#ifndef SYS_disabled0
#define SYS_disabled0 0
#endif
#ifndef SYS_disabled1
#define SYS_disabled1 0
#endif
#ifndef SYS_disabled2
#define SYS_disabled2 0
#endif
#ifndef SYS_fallback
#define SYS_fallback 0
#endif
#ifndef SYS_foo
#define SYS_foo 0
#endif
#ifndef SYS_minimize
#define SYS_minimize 0
#endif
#ifndef SYS_mutate0
#define SYS_mutate0 0
#endif
#ifndef SYS_mutate1
#define SYS_mutate1 0
#endif
#ifndef SYS_mutate2
#define SYS_mutate2 0
#endif
#ifndef SYS_mutate3
#define SYS_mutate3 0
#endif
#ifndef SYS_mutate4
#define SYS_mutate4 0
#endif
#ifndef SYS_mutate5
#define SYS_mutate5 0
#endif
#ifndef SYS_mutate6
#define SYS_mutate6 0
#endif
#ifndef SYS_mutate7
#define SYS_mutate7 0
#endif
#ifndef SYS_mutate8
#define SYS_mutate8 0
#endif
#ifndef SYS_mutate_array
#define SYS_mutate_array 0
#endif
#ifndef SYS_mutate_array2
#define SYS_mutate_array2 0
#endif
#ifndef SYS_mutate_buffer
#define SYS_mutate_buffer 0
#endif
#ifndef SYS_mutate_flags
#define SYS_mutate_flags 0
#endif
#ifndef SYS_mutate_flags2
#define SYS_mutate_flags2 0
#endif
#ifndef SYS_mutate_flags3
#define SYS_mutate_flags3 0
#endif
#ifndef SYS_mutate_integer
#define SYS_mutate_integer 0
#endif
#ifndef SYS_mutate_integer2
#define SYS_mutate_integer2 0
#endif
#ifndef SYS_mutate_rangedbuffer
#define SYS_mutate_rangedbuffer 0
#endif
#ifndef SYS_mutate_union
#define SYS_mutate_union 0
#endif
#ifndef SYS_overlay_any
#define SYS_overlay_any 0
#endif
#ifndef SYS_overlay_ctor
#define SYS_overlay_ctor 0
#endif
#ifndef SYS_overlay_uses
#define SYS_overlay_uses 0
#endif
#ifndef SYS_serialize0
#define SYS_serialize0 0
#endif
#ifndef SYS_serialize1
#define SYS_serialize1 0
#endif
#ifndef SYS_test
#define SYS_test 0
#endif
#ifndef SYS_test_excessive_args1
#define SYS_test_excessive_args1 0
#endif
#ifndef SYS_test_excessive_args2
#define SYS_test_excessive_args2 0
#endif
#ifndef SYS_test_length15
#define SYS_test_length15 0
#endif
#ifndef SYS_unsupported
#define SYS_unsupported 0
#endif
#endif

#if GOARCH_64_fork
#define GOARCH "64_fork"
#define SYZ_REVISION "bc19a08e293100957e1f6cadb9926ba73974821d"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_EXECUTOR_USES_SHMEM 0
#define SYZ_PAGE_SIZE 8192
#define SYZ_NUM_PAGES 2048
#define SYZ_DATA_OFFSET 536870912
#ifndef SYS_breaks_returns
#define SYS_breaks_returns 0
#endif
#ifndef SYS_csource0
#define SYS_csource0 0
#endif
#ifndef SYS_csource1
#define SYS_csource1 0
#endif
#ifndef SYS_csource2
#define SYS_csource2 0
#endif
#ifndef SYS_csource3
#define SYS_csource3 0
#endif
#ifndef SYS_csource4
#define SYS_csource4 0
#endif
#ifndef SYS_csource5
#define SYS_csource5 0
#endif
#ifndef SYS_csource6
#define SYS_csource6 0
#endif
#ifndef SYS_disabled0
#define SYS_disabled0 0
#endif
#ifndef SYS_disabled1
#define SYS_disabled1 0
#endif
#ifndef SYS_disabled2
#define SYS_disabled2 0
#endif
#ifndef SYS_fallback
#define SYS_fallback 0
#endif
#ifndef SYS_foo
#define SYS_foo 0
#endif
#ifndef SYS_minimize
#define SYS_minimize 0
#endif
#ifndef SYS_mutate0
#define SYS_mutate0 0
#endif
#ifndef SYS_mutate1
#define SYS_mutate1 0
#endif
#ifndef SYS_mutate2
#define SYS_mutate2 0
#endif
#ifndef SYS_mutate3
#define SYS_mutate3 0
#endif
#ifndef SYS_mutate4
#define SYS_mutate4 0
#endif
#ifndef SYS_mutate5
#define SYS_mutate5 0
#endif
#ifndef SYS_mutate6
#define SYS_mutate6 0
#endif
#ifndef SYS_mutate7
#define SYS_mutate7 0
#endif
#ifndef SYS_mutate8
#define SYS_mutate8 0
#endif
#ifndef SYS_mutate_array
#define SYS_mutate_array 0
#endif
#ifndef SYS_mutate_array2
#define SYS_mutate_array2 0
#endif
#ifndef SYS_mutate_buffer
#define SYS_mutate_buffer 0
#endif
#ifndef SYS_mutate_flags
#define SYS_mutate_flags 0
#endif
#ifndef SYS_mutate_flags2
#define SYS_mutate_flags2 0
#endif
#ifndef SYS_mutate_flags3
#define SYS_mutate_flags3 0
#endif
#ifndef SYS_mutate_integer
#define SYS_mutate_integer 0
#endif
#ifndef SYS_mutate_integer2
#define SYS_mutate_integer2 0
#endif
#ifndef SYS_mutate_rangedbuffer
#define SYS_mutate_rangedbuffer 0
#endif
#ifndef SYS_mutate_union
#define SYS_mutate_union 0
#endif
#ifndef SYS_overlay_any
#define SYS_overlay_any 0
#endif
#ifndef SYS_overlay_ctor
#define SYS_overlay_ctor 0
#endif
#ifndef SYS_overlay_uses
#define SYS_overlay_uses 0
#endif
#ifndef SYS_serialize0
#define SYS_serialize0 0
#endif
#ifndef SYS_serialize1
#define SYS_serialize1 0
#endif
#ifndef SYS_test
#define SYS_test 0
#endif
#ifndef SYS_test_excessive_args1
#define SYS_test_excessive_args1 0
#endif
#ifndef SYS_test_excessive_args2
#define SYS_test_excessive_args2 0
#endif
#ifndef SYS_test_length15
#define SYS_test_length15 0
#endif
#ifndef SYS_unsupported
#define SYS_unsupported 0
#endif
#endif

#endif

#if GOOS_trusty
#define GOOS "trusty"

#if GOARCH_arm
#define GOARCH "arm"
#define SYZ_REVISION "09df687af8477a840825c3414f68f15559d0ac60"
#define SYZ_EXECUTOR_USES_FORK_SERVER 0
#define SYZ_EXECUTOR_USES_SHMEM 0
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#endif

#endif

#if GOOS_windows
#define GOOS "windows"

#if GOARCH_amd64
#define GOARCH "amd64"
#define SYZ_REVISION "0636177e5f57801a7af2784b9d82a68cabf2e469"
#define SYZ_EXECUTOR_USES_FORK_SERVER 0
#define SYZ_EXECUTOR_USES_SHMEM 0
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
#endif

#endif

